services:
  mariadb:
    image: mariadb:latest
    container_name: aiglesend-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Rolanddev@1995
      - MYSQL_DATABASE=aiglesend
      - MYSQL_USER=aiglesendUser
      - MYSQL_PASSWORD=Rolanddev@1995
    volumes:
      - aiglesend_mariadb_data:/var/lib/mysql
      - ./config:/etc/mysql/conf.d
    networks:
      - aiglesend-network
  redis:
    image: redis:7-alpine
    container_name: aiglesend-redis
    restart: always
    ports:
      - "6378:6379"
    environment:
      - REDIS_PASSWORD=Rolanddev@1995
    volumes:
      - aiglesend_redis_data:/data/
    command: redis-server --appendonly yes --requirepass Rolanddev@1995
    networks:
      - aiglesend-network

  postgresql:
    image: postgres:16-alpine
    container_name: aiglesend-postgres
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=aiglesend
      - POSTGRES_USER=aiglesendUser
      - POSTGRES_PASSWORD=Rolanddev@1995
    volumes:
      - aiglesend_postgres_data:/var/lib/postgresql/data
    networks:
      - aiglesend-network

volumes:
  aiglesend_mariadb_data:
  aiglesend_redis_data:
  aiglesend_postgres_data:

networks:
  aiglesend-network:
    driver: bridge
