// app/shared/enums/provider_error_enums.ts

export enum ProviderErrorCode {
  INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS',
  INVALID_PHONE_NUMBER = 'INVALID_PHONE_NUMBER',
  INVALID_AMOUNT = 'INVALID_AMOUNT',
  INVALID_RECIPIENT = 'INVALID_RECIPIENT',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  FRAUD_SUSPICION = 'FRAUD_SUSPICION',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  CANCELED = 'CANCELED',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
  UNSUPPORTED_CURRENCY = 'UNSUPPORTED_CURRENCY',
  UNSUPPORTED_OPERATOR = 'UNSUPPORTED_OPERATOR',
  BLACKLISTED_NUMBER = 'BLACKLISTED_NUMBER',
  RECIPIENT_NOT_ELIGIBLE = 'RECIPIENT_NOT_ELIGIBLE',
  PROVIDER_REFUSED = 'PROVIDER_REFUSED',
  EXPIRED_SESSION = 'EXPIRED_SESSION',
  PROVIDER_UNAVAILABLE = 'PROVIDER_UNAVAILABLE',
  RATE_LIMITED = 'RATE_LIMITED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
  UNKNOWN_ERROR = 'UNKNOWN_ERROR',
}

export enum ErrorCategory {
  USER_ERROR = 'USER_ERROR',
  PROVIDER_ERROR = 'PROVIDER_ERROR',
  SECURITY = 'SECURITY',
  INTERNAL = 'INTERNAL',
}

export enum ErrorSeverity {
  DEFINITIVE = 'DEFINITIVE',
  RETRYABLE = 'RETRYABLE',
  CONFIGURATION = 'CONFIGURATION',
  AMBIGUOUS = 'AMBIGUOUS',
}

export enum AdminAction {
  REFUND = 'REFUND',
  INVESTIGATE = 'INVESTIGATE',
  REVIEW_ACCOUNT = 'REVIEW_ACCOUNT',
  ESCALATE = 'ESCALATE',
  MONITOR_PROVIDER = 'MONITOR_PROVIDER',
  NONE = 'NONE',
}
