export enum TransactionLogEvent {
  CREATED = 'CREATED',
  WALLET_DEBITED = 'WALLET_DEBITED',
  WALLET_CREDITED = 'WALLET_CREDITED',
  SENT_TO_AGGREGATOR = 'SENT_TO_AGGREGATOR',
  WEBHOOK_RECEIVED = 'WEBHOOK_RECEIVED',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  RETRY = 'RETRY',
  REFUND = 'REFUND',
  CANCELLED = 'CANCELLED',
  LEDGER_ENTRY_CREATED = 'LEDGER_ENTRY_CREATED',
}
